/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AnalogClock {}
  interface ClockDisplay {
    'hours': number;
    'minutes': number;
    'seconds': number;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
}

declare global {


  interface HTMLAnalogClockElement extends Components.AnalogClock, HTMLStencilElement {}
  var HTMLAnalogClockElement: {
    prototype: HTMLAnalogClockElement;
    new (): HTMLAnalogClockElement;
  };

  interface HTMLClockDisplayElement extends Components.ClockDisplay, HTMLStencilElement {}
  var HTMLClockDisplayElement: {
    prototype: HTMLClockDisplayElement;
    new (): HTMLClockDisplayElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'analog-clock': HTMLAnalogClockElement;
    'clock-display': HTMLClockDisplayElement;
    'my-component': HTMLMyComponentElement;
  }
}

declare namespace LocalJSX {
  interface AnalogClock extends JSXBase.HTMLAttributes<HTMLAnalogClockElement> {}
  interface ClockDisplay extends JSXBase.HTMLAttributes<HTMLClockDisplayElement> {
    'hours'?: number;
    'minutes'?: number;
    'seconds'?: number;
  }
  interface MyComponent extends JSXBase.HTMLAttributes<HTMLMyComponentElement> {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface IntrinsicElements {
    'analog-clock': AnalogClock;
    'clock-display': ClockDisplay;
    'my-component': MyComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


